// The 120 class names `assets/models/best.tflite` was trained to detect,
// in the exact index order baked into the model's output tensor (index N in
// this array === channel N of the model's [1, 124, 2100] output, after the
// first 4 bbox channels). Order matters — do not sort or edit this list.
//
// Recovered from the training dataset itself, since no labels file was saved
// alongside the exported model: Roboflow project
// food-recipe-ingredient-images-0gnku/food-ingredients-dataset, version 4
// (https://universe.roboflow.com/food-recipe-ingredient-images-0gnku/food-ingredients-dataset/dataset/4),
// via that version's frozen `data.yaml` `names:` list.
export const INGREDIENT_LABELS = [
  'Akabare Khursani',
  'Apple',
  'Artichoke',
  'Ash Gourd',
  'Asparagus',
  'Avocado',
  'Bacon',
  'Bamboo Shoots',
  'Banana',
  'Beans',
  'Beaten Rice',
  'Beef',
  'Beetroot',
  'Bethu ko Saag',
  'Bitter Gourd',
  'Black Lentils',
  'Black Beans',
  'Bottle Gourd',
  'Bread',
  'Brinjal',
  'Broad Beans',
  'Broccoli',
  'Buff Meat',
  'Butter',
  'Cabbage',
  'Capsicum',
  'Carrot',
  'Cassava',
  'Cauliflower',
  'Chayote',
  'Cheese',
  'Chicken Gizzards',
  'Chicken',
  'Chickpeas',
  'Chili Pepper',
  'Chili Powder',
  'Chowmein Noodles',
  'Cinnamon',
  'Coriander',
  'Corn',
  'Cornflakes',
  'Crab Meat',
  'Cucumber',
  'Egg',
  'Farsi ko Munta',
  'Fiddlehead Ferns',
  'Fish',
  'Garden Peas',
  'Garden Cress',
  'Garlic',
  'Ginger',
  'Green Brinjal',
  'Green Lentils',
  'Green Mint',
  'Green Peas',
  'Green Soyabean',
  'Gundruk',
  'Ham',
  'Ice',
  'Jack Fruit',
  'Ketchup',
  'Lapsi',
  'Lemon',
  'Lime',
  'Long Beans',
  'Masyaura',
  'Milk',
  'Minced Meat',
  'Moringa Leaves',
  'Mushroom',
  'Mutton',
  'Nutrela',
  'Okra',
  'Olive Oil',
  'Onion Leaves',
  'Onion',
  'Orange',
  'Palak',
  'Palungo',
  'Paneer',
  'Papaya',
  'Pea',
  'Pear',
  'Pointed Gourd',
  'Pork',
  'Potato',
  'Pumpkin',
  'Radish',
  'Rahar ko Daal',
  'Rayo ko Saag',
  'Red Beans',
  'Red Lentils',
  'Rice',
  'Sajjyun',
  'Salt',
  'Sausage',
  'Snake Gourd',
  'Soy Sauce',
  'Soyabean',
  'Sponge Gourd',
  'Stinging Nettle',
  'Strawberry',
  'Sugar',
  'Sweet Potato',
  'Taro Leaves',
  'Taro Root',
  'Thukpa Noodles',
  'Tofu',
  'Tomato',
  'Tori ko Saag',
  'Tree Tomato',
  'Turnip',
  'Walnut',
  'Watermelon',
  'Wheat',
  'Yellow Lentils',
  'Kimchi',
  'Mayonnaise',
  'Noodle',
  'Seaweed',
] as const;
